.github/dependabot.yml
.github/workflows/cla.yaml
.github/workflows/prettier.yaml
.github/workflows/profanityFilter.yaml
renovate.json

Added the common workflows for the repository:
- profanityFilter -- to check issues and PRs for profane words
- prettier -- to check and fix syntax, indentation, etc. of md, yaml, json, css and other structured files
Added basic dependabot's configuration.

Common workflows added

---

src/main/java/org/qubership/integration/platform/engine/camel/processors/context/propagation/ContextPropagationProcessorProxy.java
src/main/java/org/qubership/integration/platform/engine/camel/processors/context/propagation/ContextRestoreProcessorProxy.java

#28 Fix typo in context propagation bean names

---

src/main/java/org/qubership/integration/platform/engine/rest/v1/dto/LiveExchangeDTO.java

Added copyright notice

---

.editorconfig
.gitattributes
.github/auto-labeler-config.yaml
.github/linters/.checkov.yaml
.github/linters/.eslintrc.yml
.github/linters/.flake8
.github/linters/.golangci.yml
.github/linters/.jscpd.json
.github/linters/.yaml-lint.yml
.github/linters/actionlint.yml
.github/release-drafter-config.yml
.github/super-linter.env
.github/workflows/automatic-pr-labeler.yaml
.github/workflows/cla.yaml
.github/workflows/pr-conventional-commits.yaml
.github/workflows/pr-lint-title.yaml
.github/workflows/profanity-filter.yaml
.github/workflows/super-linter.yaml

[web-flow](https://github.com/Netcracker/qubership-integration-engine/commit/3213165969bcdf357b000cce783b2b2f6806bcca) ci: update auto labeler config
[web-flow](https://github.com/Netcracker/qubership-integration-engine/commit/4ecad50cfbdd9e5cd4c5f48b93c960a5670841bf) ci: update of editorconfig file. If changes needed please contribute to https://github.com/Netcracker/.github/blob/main/.editorconfig
[web-flow](https://github.com/Netcracker/qubership-integration-engine/commit/7b4e819a2590a393bdc841f05689ad88544d1ce2) ci: update of gitattributes file according to https://github.com/gitattributes/gitattributes templates
[web-flow](https://github.com/Netcracker/qubership-integration-engine/commit/667d62644a91433dab0b1035cedd4ef2a2d3872f) ci: update release drafter config file …

ci: update auto labeler config

---

src/main/java/org/qubership/integration/platform/engine/camel/processors/SplitAsyncProcessor.java
src/main/java/org/qubership/integration/platform/engine/camel/processors/session/ChainFinishProcessor.java
src/main/java/org/qubership/integration/platform/engine/model/Session.java
src/main/java/org/qubership/integration/platform/engine/model/opensearch/AbstractElementElastic.java
src/main/java/org/qubership/integration/platform/engine/model/opensearch/SessionElementElastic.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/CamelDebugger.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/sessions/SessionsService.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/util/DebuggerUtils.java

#85 Added separate session duration field for synchronous threads

---

src/main/java/org/qubership/integration/platform/engine/camel/components/context/propagation/ContextOperationsWrapper.java
src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/ServletCustomFilterStrategy.java
src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/binding/HandlingHttpBinding.java
src/main/java/org/qubership/integration/platform/engine/camel/context/propagation/CamelExchangeContextPropagation.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/CamelDebugger.java

#92 Fixed checkstyle issue

---

src/main/java/org/qubership/integration/platform/engine/model/logging/ElementRetryProperties.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/CamelDebugger.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/logging/ChainLogger.java

#111 Removed use of keys retryCount and retryDelay in exchange properties

---

src/main/java/org/qubership/integration/platform/engine/IntegrationEngineApplication.java
src/main/java/org/qubership/integration/platform/engine/service/IntegrationRuntimeService.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

Closes https://github.com/Netcracker/qubership-integration-engine/issues/107

Improved deployment process of Camel

---

src/main/java/org/qubership/integration/platform/engine/configuration/ExchangePropertyAutoConfiguration.java
src/main/java/org/qubership/integration/platform/engine/model/constants/CamelConstants.java
src/main/java/org/qubership/integration/platform/engine/service/ExchangePropertyService.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/CamelDebugger.java

Added bluegreenState property into exchange property

---

src/main/resources/db/migration/postgresql/static/V101_000__trigger-for-removing-checkpoint-body-blob.sql
src/main/resources/db/migration/postgresql/static/V101_001__trigger-for-removing-property-blob.sql

Implemented DB trigger to clean up large objects for removed checkpoints

---

src/main/java/org/qubership/integration/platform/engine/mapper/atlasmap/ComplexMappingAtlasModule.java
src/main/java/org/qubership/integration/platform/engine/mapper/atlasmap/json/QipAtlasJsonFieldReader.java

[Fix] Mapping array to exchange property fails for null

---

src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/exception/ChainGlobalExceptionHandler.java
src/main/java/org/qubership/integration/platform/engine/camel/processors/GrpcSenderPreProcessor.java

#154 Not able to handle errors when using Service Call with gRPC

---

src/main/resources/db/migration/postgresql/static/V103_000__context-storage.sql

CIP-8 fixing migration file issue

---

src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/CustomCamelHttpTransportServlet.java
src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/CustomHttpRestServletResolveConsumerStrategy.java
src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/RestConsumerContextPathCustomMatcher.java
src/main/java/org/qubership/integration/platform/engine/configuration/camel/CamelServletConfiguration.java

fix: [v0.1] #220 Fixed an issue where an endpoint with a path parameter containing the "_" symbol could fail on register

---

src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/CustomCamelHttpTransportServlet.java
src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/CustomHttpRestServletResolveConsumerStrategy.java
src/main/java/org/qubership/integration/platform/engine/camel/components/servlet/RestConsumerContextPathCustomMatcher.java
src/main/java/org/qubership/integration/platform/engine/configuration/camel/CamelServletConfiguration.java

fix: #220 Fixed an issue where an endpoint with a path parameter containing the "_" symbol could fail on register

---

src/main/java/org/qubership/integration/platform/engine/camel/processors/checkpoint/ContextLoaderProcessor.java
src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Checkpoint.java
src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Property.java
src/main/resources/db/migration/postgresql/static/V104_000__deprecate_oid_fields.sql

Closes https://github.com/Netcracker/qubership-integration-engine/issues/223

Fix for oid performance issue

---

src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Checkpoint.java
src/main/resources/application-development.yml
src/main/resources/application.yml

fix: [v0.1] #241 Added optimizations for insert and delete operations for checkpoints

---

src/main/java/org/qubership/integration/platform/engine/persistence/shared/entity/Checkpoint.java
src/main/resources/application-development.yml
src/main/resources/application.yml

fix: #241 Added optimizations for insert and delete operations for checkpoints

---

.github/workflows/maven-release-v2.yaml

Related issue: https://github.com/Netcracker/.github/issues/136

feat(ci): Broadcast maven-release-v2 workflow to QIP repos

---

src/main/java/org/qubership/integration/platform/engine/camel/processors/HttpTriggerFinishProcessor.java
src/main/java/org/qubership/integration/platform/engine/camel/processors/session/ChainFinishProcessor.java
src/main/java/org/qubership/integration/platform/engine/model/constants/CamelConstants.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/CamelDebugger.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/sessions/SessionsService.java
src/main/java/org/qubership/integration/platform/engine/service/debugger/util/MaskedFieldUtils.java

Enhancement: Updated chain masking logic so that masked field settings from a parent chain automatically apply to its sub-chains.
This combines the parent and sub-chain masked fields lists for more consistent and secure logging.
Improves clarity, reduces configuration errors, and ensures sensitive data remains masked across chained executions.

feat: Chain masking
